//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4H_VFMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tblDriverList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDriverList()
        {
            this.tblVehicleAssignments = new HashSet<tblVehicleAssignment>();
        }
    
        public int Id { get; set; }
        [DisplayName("Title")]
        public int dTitle { get; set; }
        [DisplayName("Firstname")]
        public string dFirstName { get; set; }
        [DisplayName("Lastname")]
        public string dLastName { get; set; }
        [DisplayName("Gender")]
        public int dGender { get; set; }
        [DisplayName("Position")]
        public int dPosition { get; set; }
        [DisplayName("License#")]
        public string dLicense { get; set; }
        [DisplayName("LicenseExp.")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public string dLicenseExpiry { get; set; }
        [DisplayName("CreareBy")]
        public string createdBy { get; set; }
        [DisplayName("DateCreated")]
        public Nullable<System.DateTime> dateCreated { get; set; }
        [DisplayName("UpdateBy")]
        public string updatedBy { get; set; }
        [DisplayName("DateUpdated")]
        public Nullable<System.DateTime> dateUpdated { get; set; }
        [DisplayName("DeleteBy")]
        public string deletedBy { get; set; }
        [DisplayName("DeleteFlag")]
        public string deleteFlag { get; set; }
        [DisplayName("DateDeleted")]
        public Nullable<System.DateTime> dateDeleted { get; set; }
        [DisplayName("Available")]
        public string dStatus { get; set; }
    
        public virtual gender gender { get; set; }
        public virtual position position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVehicleAssignment> tblVehicleAssignments { get; set; }
        public virtual title title { get; set; }
    }
}
