//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4H_VFMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tblVehicleAssignment
    {
        public int Id { get; set; }
        [DisplayName("Driverid")]
        public int dId { get; set; }
        [DisplayName("Vehicleid")]
        public int vId { get; set; }
        [DisplayName("AssignoutDate")]
        public Nullable<System.DateTime> vAssignOutDate { get; set; }
        [DisplayName("Assignduration")]
        public int vAssignDuration { get; set; }
        [DisplayName("Assignindate")]
        public Nullable<System.DateTime> vAssignInDate { get; set; }
        [DisplayName("Assignused")]
        public Nullable<int> vAssignUsed { get; set; }
        [DisplayName("Mileageout")]
        public int vMileageOut { get; set; }
        [DisplayName("Mileagein")]
        public Nullable<int> vMileageIn { get; set; }
        [DisplayName("Milestravelle")]
        public Nullable<int> vMileageTravelled { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
    
        public virtual tblDriverList tblDriverList { get; set; }
        public virtual tblVehicleList tblVehicleList { get; set; }
    }

}
