//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4H_VFMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tblVehicleList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVehicleList()
        {
            this.tblVehicleAssignments = new HashSet<tblVehicleAssignment>();
        }
    
        public int Id { get; set; }
        [DisplayName("Type")]
        public int vType { get; set; }
        [DisplayName("Year")]
        public int vYear { get; set; }
        [DisplayName("Colour")]
        public int vColour { get; set; }
        [DisplayName("Transtype")]
        public int vTransType { get; set; }
        [DisplayName("Licenseplate")]
        public string vLicPlate { get; set; }
        [DisplayName("Status")]
        public int vStatus { get; set; }
        [DisplayName("CreatedBy")]
        public string createdBy { get; set; }
        [DisplayName("DateCreated")]
        public Nullable<System.DateTime> dateCreated { get; set; }
        [DisplayName("UpdatedBy")]
        public string updatedBy { get; set; }
        [DisplayName("DateUpdated")]
        public Nullable<System.DateTime> dateUpdated { get; set; }
        [DisplayName("DeletedBy")]
        public string deletedBy { get; set; }
        [DisplayName("DeleteFlag")]
        public string deleteFlag { get; set; }
        [DisplayName("DateDeleted")]
        public Nullable<System.DateTime> dateDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVehicleAssignment> tblVehicleAssignments { get; set; }
        public virtual vColour vColour1 { get; set; }
        public virtual vStatu vStatu { get; set; }
        public virtual vTransType vTransType1 { get; set; }
        public virtual vType vType1 { get; set; }
        public virtual vYear vYear1 { get; set; }
    }
}
