//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4H_VFMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VFMS_DBEntities : DbContext
    {
        public VFMS_DBEntities()
            : base("name=VFMS_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<gender> genders { get; set; }
        public virtual DbSet<position> positions { get; set; }
        public virtual DbSet<tblDriverList> tblDriverLists { get; set; }
        public virtual DbSet<tblUserList> tblUserLists { get; set; }
        public virtual DbSet<tblVehicleAssignment> tblVehicleAssignments { get; set; }
        public virtual DbSet<tblVehicleList> tblVehicleLists { get; set; }
        public virtual DbSet<title> titles { get; set; }
        public virtual DbSet<vColour> vColours { get; set; }
        public virtual DbSet<vStatu> vStatus { get; set; }
        public virtual DbSet<vTransType> vTransTypes { get; set; }
        public virtual DbSet<vType> vTypes { get; set; }
        public virtual DbSet<vYear> vYears { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
